- name: Create folder to store client files
  file:
    path: "/home/ubuntu/vpn_users/{{ username }}"
    state: directory

- name: "Build client keys"
  command: ./easyrsa --batch --req-cn="{{ username }}" gen-req {{ username }} nopass
  args:
    chdir: "{{ca_dir}}/easyrsa3"
    creates: "{{ca_dir}}/easyrsa3/pki/private/{{ username }}.key"

- name: "Sign client keys"
  command: ./easyrsa --batch sign-req client {{ username }}
  args:
    chdir: "{{ca_dir}}/easyrsa3"
    creates: "{{ca_dir}}/easyrsa3/pki/issued/{{username}}.crt"

- name: Copy ta.key
  become: true
  shell: "cp /etc/openvpn/ta.key /home/ubuntu/vpn_users/{{username}}/ta.key"
  args:
    creates: "/home/ubuntu/vpn_users/{{ username }}/ta.key"

- name: Copy certification files
  become: true
  shell: "cp {{ ca_dir }}/easyrsa3/pki/{{ item }} /home/ubuntu/vpn_users/{{username}}"
  args:
    creates: "/home/ubuntu/vpn_users/{{ username }}/{{ item }}"
  with_items:
    - "private/{{username}}.key"
    - "ca.crt"
    - "issued/{{username}}.crt"

- name: Generate the OpenVPN client config
  template:
    src: openvpn_client.ovpn.j2
    dest: "/home/ubuntu/vpn_users/{{ username }}/{{ username }}.ovpn"
