- name: Install dnsmasq
  become: yes
  package:
   name: dnsmasq
   state: present

- name: Copy dnsmasq configuration file
  become: yes
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf

- name: Restart the dnsmasq service
  become: yes
  service:
    name: "dnsmasq"
    enabled: yes
    state: restarted
